name: Download SoundCloud Playlist

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 
python3-pip ffmpeg
          pip3 install soundcloud-downloader

      - name: Download SoundCloud Playlist
        env:
          PLAYLIST_URL: $
{{ secrets.SOUNDCLOUD_URL }}
        run: |
          mkdir -p downloads
          scdl -l "$PLAYLIST_URL" -o
downloads/ --path-template "{artist}/{title}"

      - name: Upload playlist to artifact
        uses: actions/upload-artifact@v3
        with:
          name: soundcloud-playlist
          path: downloads
